name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: ["main"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        example: [examples/Lock/Lock.ino]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio lib -g install "obsttube/CryptoAES_CBC@^1.0.0"
          pio lib -g install "h2zero/NimBLE-Arduino@^1.4.0"
      - name: Run PlatformIO
        run: |
          pio ci --lib="." --board=esp32dev
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}